### ISSUE TITLE
Problème de démarrage

### ISSUE THREAD

**Issue by tresorier21000** [jtpaquet/PiCamera-GUI#2]
Bonjour,
Je débute avec mon raspberry et ma caméra !
J'ai découvert votre interface graphique qui répond bien à mon besoin et qui semble très facile à utiliser.

Malheureusement, après avoir suivi votre excellent guide de mise en oeuvre, je bute sur le lancement du programme main.py.
J'ai respecté la même structure que votre guide (installation de l'application dans Camera_module)

Voici le fichier que j'ai récupéré au lancement :

Python 3.5.3 (/usr/bin/python3)
>>> %Run main.py
Initialisation de la fenêtre
Traceback (most recent call last):
  File "/home/pi/Camera_module/picamera-gui/main.py", line 39, in <module>
    run()
  File "/home/pi/Camera_module/picamera-gui/main.py", line 31, in run
    app = PiCameraGUI(win,camera,title="PiCamera")
  File "/home/pi/Camera_module/picamera-gui/PiCameraGUI.py", line 88, in __init__
    self.createFrames()
  File "/home/pi/Camera_module/picamera-gui/PiCameraGUI.py", line 154, in createFrames
    self.imagedefaut = PhotoImage(file=ASSETS_DIR+"default.png")
  File "/usr/lib/python3.5/tkinter/__init__.py", line 3406, in __init__
    Image.__init__(self, 'photo', name, cnf, master, **kw)
  File "/usr/lib/python3.5/tkinter/__init__.py", line 3362, in __init__
    self.tk.call(('image', 'create', imgtype, name,) + options)
_tkinter.TclError: couldn't open "./Assets/default.png": no such file or directory
>>> 

L'interface s'ouvre bien, mais le programme s'arrête.
Je ne suis malheureusement pas très avancé en python pour décrypter tous les messages.

Merci de l'aide que vous pourriez m'apporter

YB
tresorier21000@gmail.com

**Comment by sudeephazra** [comment]
The code is trying to find the Assets folder inside your working directory but unable to do so. If you run the command from one level up, it should do the trick.
 
Please run the following 
```
$> cd /home/pi/Camera_module/
$> python3 picamera-gui/main.py
```
